version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: bank-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"